### ISSUE TITLE
New dictionary built-in

### ISSUE THREAD

**Issue by billtubbs** [MartinKoch123/yaml#10]
Did you hear about this?

- [An introduction to dictionaries (associative arrays) in MATLAB](https://blogs.mathworks.com/matlab/2022/09/15/an-introduction-to-dictionaries-associative-arrays-in-matlab/)

Any thoughts on whether this impacts yaml?

**Comment by MartinKoch123** [comment]
Hey, I only found the time now to answer. I think the new dictionaries are probably better to represent YAML maps than structs since there are no restrictions on the key. However I won't make it the default now to support older MATLAB versions. Maybe I'll add an option to switch to dictionaries. Thanks for the hint!

**Comment by billtubbs** [comment]
Yeah, I wouldn't change anything to soon. The struct has been the main alternative to dictionaries since the beginning so I expect most people including me still use it (I tried `containers.Map` and gave up on that pretty quick!). I guess it will take a few years before everyone's using dictionaries.
