### ISSUE TITLE
performence bechmarks

### ISSUE THREAD

**Issue by qlahcim** [MartinKoch123/yaml#7]
Are there any performance benchmarks? How compare this parser with other MATLAB parsers available regarding large YAML files?

**Comment by MartinKoch123** [comment]
I'm not aware of any benchmarks. To the best of my knowledge, all other MATLAB parsers are based on snakeyaml as well and I therefore expect the performance to be very similar.

**Comment by qlahcim** [comment]
I am using many, many ... years still the same YAML parser [YAMLMatlab](https://code.google.com/archive/p/yamlmatlab/), which was really excellent solution. But its development is dead from 2012 and now is really a bit obsolete. So, I am looking now for some new YAML parser for MATLAB compatible with latest YAML specs, which is fast and simple as possible from user point of view. I need up to date (YAML specs), robust and fast(!!!) YAML parser for my MATLAB projects as an integral part of my workflow.

Your parser looks, so far, really good!!! 

What were your main goals in developing a new YAML parser when there are many other similar YAML parsers available for MATLAB? And most of them are based on the same YAML engine - snakeyaml! What are the key or unique features of your parser?

**Comment by MartinKoch123** [comment]
I'm glad you like it. I have also been using YAMLMatlab until I made this repo. My goals were to
- update the snakeyaml-wrapper to modern Matlab (string types, type hints, argument validation), 
- give it the most obvious and simple user interface I could think of 
- have good error handling 
- provide a documentation
- and write short and readable code using modern Matlab features.

The actual parsing is still done by snakeyaml and I wont change that since it seems to be a very complex task to write a good parser.

**Comment by qlahcim** [comment]
So, performance (speed, low memory footprint) on large or complex YAML files was not your goal... OK.

**Comment by MartinKoch123** [comment]
Correct
